site_name: Dev-Wiki
site_url: https://example.com
Home: index.md
theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
plugins:
  - search
  - roamlinks
