site_name: quwiki
site_url: https://gramding.github.io/MKDOCS_TEST/
site_dir: public
docs_dir: ./docs

theme:
  name: material
  palette:
    scheme: slate
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true

plugins:
    - search:
        indexing: 'full'
    - roamlinks
    - callouts
